version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: calculator
      POSTGRES_USER: admin-calculator
      POSTGRES_PASSWORD: clojure_is_cool
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    environment:
      DB_NAME: calculator
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: admin-calculator
      DB_PASSWORD: clojure_is_cool
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  db_data: